# Generated by Django 3.2.2 on 2024-11-25 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rtlh_admin.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kriteria', models.CharField(max_length=300)),
                ('desk_singkat', models.CharField(max_length=300)),
                ('desk_detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='data_rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.CharField(max_length=20, null=True)),
                ('nik', models.CharField(max_length=20, null=True)),
                ('nama_kk', models.CharField(max_length=300)),
                ('pendidikan', models.CharField(max_length=300, null=True)),
                ('jenis_kelamin', models.CharField(max_length=300, null=True)),
                ('tempat_lahir', models.CharField(max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(null=True)),
                ('agama', models.CharField(max_length=300)),
                ('alamat_lengkap', models.CharField(max_length=300, null=True)),
                ('kelurahan', models.CharField(max_length=300, null=True)),
                ('jumlah_anggota', models.CharField(max_length=300, null=True)),
                ('no_hp', models.CharField(max_length=20, null=True)),
                ('pekerjaan', models.CharField(max_length=300, null=True)),
                ('penghasilan', models.CharField(max_length=300, null=True)),
                ('keterangan', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('posting', 'Posting')], default='posting', max_length=50)),
                ('email_verification_token', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', rtlh_admin.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='verifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_verifikasi', models.DateField(null=True)),
                ('status_pengajuan', models.CharField(max_length=300, null=True)),
                ('alasan', models.CharField(max_length=300, null=True)),
                ('nama_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifikasi', to='rtlh_admin.data_rumah')),
            ],
        ),
        migrations.CreateModel(
            name='permohonan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_ktp', models.ImageField(upload_to='media/')),
                ('img_kk', models.ImageField(upload_to='media/')),
                ('img_rumah', models.ImageField(upload_to='media/')),
                ('img_sertifikat', models.ImageField(upload_to='media/')),
                ('nama_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permohonan', to='rtlh_admin.data_rumah')),
            ],
        ),
        migrations.CreateModel(
            name='keterangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=300, null=True)),
                ('kerusakan', models.CharField(blank=True, max_length=300, null=True)),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keterangan', to='rtlh_admin.data_kriteria')),
            ],
        ),
        migrations.CreateModel(
            name='data_rtlh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_tanah', models.CharField(max_length=300)),
                ('status_kepemilikan', models.CharField(max_length=300)),
                ('luas_tanah', models.CharField(max_length=300)),
                ('status_rumah', models.CharField(max_length=300)),
                ('luas_bangunan', models.CharField(max_length=300)),
                ('kondisi_pondasi', models.CharField(max_length=300)),
                ('kondisi_atap', models.CharField(max_length=300)),
                ('kondisi_lantai', models.CharField(max_length=300)),
                ('kondisi_dinding', models.CharField(max_length=300)),
                ('kondisi_ventilasi', models.CharField(max_length=300)),
                ('kondisi_toilet', models.CharField(max_length=300)),
                ('sumber_airbersih', models.CharField(max_length=300)),
                ('sumber_listrik', models.CharField(max_length=300)),
                ('img_rumah', models.ImageField(upload_to='media/')),
                ('kriteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtlh_kriteria', to='rtlh_admin.data_rumah')),
                ('nama_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtlh', to='rtlh_admin.data_rumah')),
            ],
        ),
    ]
