# Generated by Django 3.2.2 on 2024-11-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_rtlh',
            name='kriteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rtlh_kriteria', to='rtlh_admin.data_kriteria'),
        ),
    ]
