# Generated by Django 3.2.2 on 2024-11-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0002_alter_data_rtlh_kriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_kriteria',
            name='desk_full',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
