# Generated by Django 3.2.2 on 2025-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0003_data_kriteria_desk_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='undang_undang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('deskripsi', models.CharField(max_length=300, null=True)),
                ('img_uu', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
