# Generated by Django 3.2.2 on 2025-01-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0007_auto_20250107_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=300)),
                ('no_hp', models.CharField(max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
