# Generated by Django 3.2.2 on 2025-01-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0008_kontak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='keterangan',
        ),
    ]
