# Generated by Django 3.2.2 on 2025-01-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0009_delete_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_kriteria',
            name='img_kriteria',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
