# Generated by Django 3.2.2 on 2025-01-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0010_data_kriteria_img_kriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_rtlh',
            name='img_rumah',
        ),
        migrations.RemoveField(
            model_name='permohonan',
            name='img_kk',
        ),
        migrations.RemoveField(
            model_name='permohonan',
            name='img_ktp',
        ),
        migrations.RemoveField(
            model_name='permohonan',
            name='img_rumah',
        ),
        migrations.RemoveField(
            model_name='permohonan',
            name='img_sertifikat',
        ),
        migrations.RemoveField(
            model_name='sekilas_info',
            name='img_info',
        ),
        migrations.RemoveField(
            model_name='undang_undang',
            name='img_uu',
        ),
        migrations.AlterField(
            model_name='data_kriteria',
            name='img_kriteria',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
