# Generated by Django 3.2.2 on 2025-01-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0012_auto_20250109_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_kriteria',
            name='img_kriteria',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='data_rtlh',
            name='img_rumah',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='img_kk',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='img_ktp',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='img_rumah',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='permohonan',
            name='img_sertifikat',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sekilas_info',
            name='img_info',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
