# Generated by Django 3.2.2 on 2025-01-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0014_auto_20250109_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_rtlh',
            name='tgl_input',
            field=models.DateField(null=True),
        ),
    ]
