# Generated by Django 3.2.2 on 2025-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0019_auto_20250115_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons_tips/'),
        ),
    ]
