# Generated by Django 3.2.2 on 2025-01-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0020_alter_tips_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_kriteria',
            old_name='img_kriteria',
            new_name='img_rumah',
        ),
    ]
