# Generated by Django 3.2.2 on 2025-01-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0021_rename_img_kriteria_data_kriteria_img_rumah'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='img_informasi',
            field=models.ImageField(null=True, upload_to='informasi/'),
        ),
    ]
