# Generated by Django 3.2.2 on 2025-01-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0022_informasi_img_informasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_kriteria',
            name='img_rumah',
        ),
        migrations.AddField(
            model_name='data_kriteria',
            name='img_tipe',
            field=models.ImageField(null=True, upload_to='tipe/'),
        ),
    ]
