# Generated by Django 3.2.2 on 2025-01-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_admin', '0023_auto_20250115_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_rumah',
            name='keterangan',
        ),
    ]
