# Generated by Django 3.2 on 2024-10-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daftar_rumah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(max_length=300)),
                ('keterangan', models.CharField(max_length=300)),
                ('kriteria', models.CharField(max_length=300)),
            ],
        ),
    ]
