# Generated by Django 3.2 on 2024-10-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beranda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=300)),
                ('sub_judul', models.CharField(max_length=300)),
                ('berita', models.TextField()),
                ('created_at', models.DateField()),
            ],
        ),
    ]
