# Generated by Django 3.2 on 2024-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail_daftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kk', models.CharField(max_length=300)),
                ('alamat', models.CharField(max_length=300)),
                ('pekerjaan', models.CharField(max_length=300)),
                ('status_rtlh', models.CharField(max_length=300)),
                ('status_pengajuan', models.CharField(max_length=300)),
            ],
        ),
    ]
