# Generated by Django 3.2 on 2024-10-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0002_beranda'),
        ('rtlh_app', '0003_auto_20241004_1535'),
    ]

    operations = [
    ]
