# Generated by Django 3.2 on 2024-11-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0004_merge_0002_beranda_0003_auto_20241004_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beranda',
        ),
    ]
