# Generated by Django 3.2.2 on 2024-11-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0005_delete_beranda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daftar_rumah',
        ),
        migrations.DeleteModel(
            name='data_rumah',
        ),
    ]
