# Generated by Django 3.2 on 2025-01-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0005_delete_beranda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peraturan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='uploads/peraturan/', verbose_name='Gambar')),
            ],
        ),
    ]
