# Generated by Django 3.2 on 2025-01-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0006_auto_20241128_1636'),
        ('rtlh_app', '0006_peraturan'),
    ]

    operations = [
    ]
