# Generated by Django 3.2 on 2025-01-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtlh_app', '0007_merge_0006_auto_20241128_1636_0006_peraturan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peraturan',
        ),
    ]
