from .dashboard import *
from .formrmh import *
from .register import *
from .profile import *
from .kriteria import *
from .user import *
from .bantuan import *
from .auth import *
from .verif import *
from .rtlh import *
from .info import *
from .undang import *
from .sekilas import *
from .krirtlh import *
from .tipsrtlh import *
from .kontakhub import *
from .laporan import *
