from .dashboard import *
from .formrmh import *
from .register import *
from .profile import *
from .kriteria import *
from .user import *
from .bantuan import *
from .auth import *
from .ket import *
from .verif import *
from .rtlh import *
from .info import *
from .ubah import *